

export const GET_TODOS_DATA_REQUEST="GET_TODOS_DATA_REQUEST";
export const GET_TODOS_DATA_SUCCESS="GET_TODOS_DATA_SUCCESS";
export const GET_TODOS_DATA_FAILURE="GET_TODOS_DATA_FAILURE";



export const ADD_TODOS_DATA_REQUEST="ADD_TODOS_DATA_REQUEST";
export const ADD_TODOS_DATA_SUCCESS="ADD_TODOS_DATA_SUCCESS";
export const ADD_TODOS_DATA_FAILURE="ADD_TODOS_DATA_FAILURE";